[AssTroopers.X2Item_Assault_Shotguns]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;T1 SHOTGUN;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

ADVENT_SHOTGUN_MAGNETIC_RANGE[0] = 0
ADVENT_SHOTGUN_MAGNETIC_RANGE[1] = 60
ADVENT_SHOTGUN_MAGNETIC_RANGE[2] = 60
ADVENT_SHOTGUN_MAGNETIC_RANGE[3] = 45
ADVENT_SHOTGUN_MAGNETIC_RANGE[4] = 30
ADVENT_SHOTGUN_MAGNETIC_RANGE[5] = 15
ADVENT_SHOTGUN_MAGNETIC_RANGE[6] = 8
ADVENT_SHOTGUN_MAGNETIC_RANGE[7] = 4
ADVENT_SHOTGUN_MAGNETIC_RANGE[8] = 0
ADVENT_SHOTGUN_MAGNETIC_RANGE[9] = 0
ADVENT_SHOTGUN_MAGNETIC_RANGE[10] = -4
ADVENT_SHOTGUN_MAGNETIC_RANGE[11] = -8
ADVENT_SHOTGUN_MAGNETIC_RANGE[12] = -16
ADVENT_SHOTGUN_MAGNETIC_RANGE[13] = -32
ADVENT_SHOTGUN_MAGNETIC_RANGE[14] = -40
ADVENT_SHOTGUN_MAGNETIC_RANGE[15] = -48
ADVENT_SHOTGUN_MAGNETIC_RANGE[16] = -60
ADVENT_SHOTGUN_MAGNETIC_RANGE[17] = -70
ADVENT_SHOTGUN_MAGNETIC_RANGE[18] = -80
ADVENT_SHOTGUN_MAGNETIC_RANGE[19] = -90
ADVENT_SHOTGUN_MAGNETIC_RANGE[20] = -100
ADVENT_SHOTGUN_MAGNETIC_RANGE[21] = -100
ADVENT_SHOTGUN_MAGNETIC_RANGE[22] = -100
ADVENT_SHOTGUN_MAGNETIC_RANGE[23] = -100
ADVENT_SHOTGUN_MAGNETIC_RANGE[24] = -100
ADVENT_SHOTGUN_MAGNETIC_RANGE[25] = -100

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;T2 SHOTGUN;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;T3 SHOTGUN;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[0] = 0
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[1] = 60
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[2] = 60
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[3] = 45
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[4] = 30
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[5] = 15
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[6] = 8
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[7] = 4
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[8] = 0
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[9] = 0
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[10] = -4
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[11] = -8
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[12] = -16
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[13] = -32
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[14] = -40
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[15] = -48
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[16] = -60
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[17] = -70
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[18] = -80
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[19] = -90
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[20] = -100
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[21] = -100
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[22] = -100
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[23] = -100
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[24] = -100
ADVENT_SHOTGUN_T3_MAGNETIC_RANGE[25] = -100


[TedModJamForLWOTC.X2Item_AssaultGrenades]

+MAG_BOMB_BASEDAMAGE = (Damage=5, Spread = 1, PlusOne = 0, Crit = 0, Pierce = 0, Shred=4, Tag = "", DamageType="Projectile_MagXCom")

+MAG_BOMB_ISOUNDRANGE=30
+MAG_BOMB_IENVIRONMENTDAMAGE=25
+MAG_BOMB_TRADINGPOSTVALUE=25
+MAG_BOMB_IPOINTS=0
+MAG_BOMB_ICLIPSIZE=1
+MAG_BOMB_RANGE=11
+MAG_BOMB_RADIUS=6

+MAG_BOMB_SUPPLY_COST=20
+MAG_BOMB_ALLOY_COST=5
+MAG_BOMB_ELERIUM_COST=0
+MAG_BOMB_CORE_COST=0

+MAG_BOMB_KNOCKBACK_DISTANCE=4

+LASER_BOMB_BASEDAMAGE = (Damage=7, Spread = 1, PlusOne = 0, Crit = 0, Pierce = 99, Shred=0, Tag = "", DamageType="Projectile_BeamXCom")

+LASER_BOMB_ISOUNDRANGE=30
+LASER_BOMB_IENVIRONMENTDAMAGE=15
+LASER_BOMB_TRADINGPOSTVALUE=25
+LASER_BOMB_IPOINTS=0
+LASER_BOMB_ICLIPSIZE=1
+LASER_BOMB_RANGE=11
+LASER_BOMB_RADIUS=6

+LASER_BOMB_SUPPLY_COST=40
+LASER_BOMB_ALLOY_COST=10
+LASER_BOMB_ELERIUM_COST=15
+LASER_BOMB_CORE_COST=1