[APGrenadesReduxLWOTC.X2Item_APGrenades]

; These options are for AP Grenades (tier 1) only
APGRENADE_BASEDAMAGE = (Damage = 2, Spread = 0, PlusOne = 50, Crit = 0, Pierce = 2, Shred = 0, Tag = "", DamageType="Projectile_Conventional")
APGRENADE_ISOUNDRANGE = 30
APGRENADE_IENVIRONMENTDAMAGE = 0
APGRENADE_ICLIPSIZE = 1
APGRENADE_RANGE = 10
APGRENADE_RADIUS = 4

; These options are for Alloy Grenades (tier 2) only
APGRENADE_MK2_BASEDAMAGE = (Damage = 4, Spread = 0, PlusOne = 50, CRIT = 0, Pierce = 4, Shred = 0, Tag = "", DamageType="Projectile_Conventional")
APGRENADE_MK2_ISOUNDRANGE = 30
APGRENADE_MK2_IENVIRONMENTDAMAGE = 0
APGRENADE_MK2_ICLIPSIZE = 1
APGRENADE_MK2_RANGE = 10
APGRENADE_MK2_RADIUS = 5
APGRENADE_MK2_TRADINGPOSTVALUE = 5

[TedModJamForLWOTC.X2Item_APGrenades]
; These options are for Alloy Bomb (tier 3) only
APGRENADE_MK3_BASEDAMAGE = (Damage = 4, Spread = 0, PlusOne = 50, Crit = 0, Pierce = 6, Shred = 0, Tag = "", DamageType="Projectile_Conventional")
APGRENADE_MK3_ISOUNDRANGE = 30
APGRENADE_MK3_IENVIRONMENTDAMAGE = 0
APGRENADE_MK3_ICLIPSIZE = 1
APGRENADE_MK3_RANGE = 11
APGRENADE_MK3_RADIUS = 6
APGRENADE_MK3_TRADINGPOSTVALUE = 5
