;A configuration File

[AvatarShowdown]
AvatarsToKill_Rookie=5
AvatarsToKill_Veteran=5
AvatarsToKill_Commander=5
AvatarsToKill_Legend=5

LargeAvatarGroups_Rookie=2
LargeAvatarGroups_Veteran=2
LargeAvatarGroups_Commander=2
LargeAvatarGroups_Legend=2
